In [2]:
import pandas as pd 
import numpy as np 

df = pd.read_csv("../data/train.csv")

df.head()

         date  store  item  sales
0  2013-01-01      1     1     13
1  2013-01-02      1     1     11
2  2013-01-03      1     1     14
3  2013-01-04      1     1     13
4  2013-01-05      1     1     10

In [4]:
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

Shape: (913000, 4)

Columns:
Index(['date', 'store', 'item', 'sales'], dtype='str')

Data Types:
date       str
store    int64
item     int64
sales    int64
dtype: object

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 913000 entries, 0 to 912999
Data columns (total 4 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   date    913000 non-null  str
 1   store   913000 non-null  int64
 2   item    913000 non-null  int64
 3   sales   913000 non-null  int64
dtypes: int64(3), str(1)
memory usage: 36.6 MB

In [6]:
df.isnull().sum()

date     0
store    0
item     0
sales    0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.describe()

               store           item          sales
count  913000.000000  913000.000000  913000.000000
mean        5.500000      25.500000      52.250287
std         2.872283      14.430878      28.801144
min         1.000000       1.000000       0.000000
25%         3.000000      13.000000      30.000000
50%         5.500000      25.500000      47.000000
75%         8.000000      38.000000      70.000000
max        10.000000      50.000000     231.000000

In [9]:
df["date"] = pd.to_datetime(df["date"])

print("Start Date:", df["date"].min())
print("End Date:", df["date"].max())

Start Date: 2013-01-01 00:00:00
End Date: 2017-12-31 00:00:00

In [10]:
print("Stores:", df["store"].nunique())
print("Items:", df["item"].nunique())

Stores: 10
Items: 50

In [13]:
sales_by_store = df.groupby("store")["sales"].sum().sort_values(ascending=False)

print(sales_by_store)

store
2     6120128
8     5856169
3     5435144
10    5360158
9     5025976
4     5012639
1     4315603
5     3631016
6     3627670
7     3320009
Name: sales, dtype: int64

In [15]:
sales_by_item = df.groupby("item")["sales"].sum().sort_values(ascending=False)

print(sales_by_item.head(10))

item
15    1607442
28    1604713
13    1539621
18    1538876
25    1473334
45    1471467
38    1470330
22    1469971
36    1406548
8     1405108
Name: sales, dtype: int64